### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by rantoniuk** [SSLcom/esigner-codesign#12]
We're getting `Java heap space` error on:

```
C:\Windows\system32\cmd.exe -/c CodeSignTool-v1.2.7-windows\CodeSignTool.bat sign -username=*** -*** -credential_id=*** -totp_secret=*** -input_file_path=Output\unsigned.exe -output_dir_path=Output\signed -override=false -malware_block=true
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

@bayrakmustafa, is there any way to pass Xmx to the action to raise the memory used by the action to circumvent this?

**Comment by bayrakmustafa** [comment]
@rantoniuk, I added `jvm_max_memory` to Github action input parameters. (https://github.com/SSLcom/esigner-codesign/blob/develop/.github/workflows/test.yml#L43) I sent it to develop branch. Can you test it?

**Comment by rantoniuk** [comment]
Tested and working perfectly, thanks for quick reaction!

**Comment by tylerdmace** [comment]
I'm trying to run the Windows docker image and am running into the same JVM OutOfMemoryError. Any work-arounds here?
