### ISSUE TITLE
Documentation clarification - How do I use batch_sign?

### ISSUE THREAD

**Issue by djbreen7** [SSLcom/esigner-codesign#2]
I have a workflow that produces multiple artifacts. I'm betting `batch_sign` is the most optimal command. It doesn't look like this action supports `input_dir_path` like the example on https://www.ssl.com/guide/esigner-codesigntool-command-guide/

Does `batch_sign` work with this action as-is, or does it need to be modified to accept `input_dir_path`?

**Comment by bayrakmustafa** [comment]
@djbreen7 I worked on the batch_sign command. I also updated the github action's tests. https://github.com/SSLcom/esigner-codesign/blob/develop/.github/workflows/test.yml#L111 can you test it by updating on your own CI/CD according to the test here
